version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - schedulegenius_pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  schedulegenius_pgdata: