apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/Users/ashwinchandrasekaran/Desktop/Data-Scale-Computing/Final_Project/TestApp/schedulegenius/data/postgres
